# Skill 元数据定义
# 此文件用于描述该 Skill 的输入输出结构，便于开发者理解和维护。
# 目前仅作为文档参考，不参与实际运行逻辑校验。

name: Write
version: 1.0

# 输入参数定义
input_schema:
  outline: list               # 文章大纲
  research_data: string       # 研究笔记
  length_constraints: object  # 长度限制 (min, max)
  banned_words: list          # 违禁词列表

# 输出结果定义
output_schema:
  draft: string               # 文章初稿

