# Skill 元数据定义
# 此文件用于描述该 Skill 的输入输出结构，便于开发者理解和维护。
# 目前仅作为文档参考，不参与实际运行逻辑校验。

name: Topic Selection
version: 1.0

# 输入参数定义
input_schema:
  niche: string   # 细分领域
  trends: list    # 趋势列表

# 输出结果定义
output_schema:
  selected_topic: string  # 选定的主题
  rationale: string       # 选择理由
  keywords: list          # 提取的关键词

